"""empty message

Revision ID: a1b99cbcd84a
Revises: 0e2070a2b939
Create Date: 2021-03-23 14:30:27.906703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b99cbcd84a'
down_revision = '0e2070a2b939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('created', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'created')
    # ### end Alembic commands ###
